openapi: 3.0.3

info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.27
servers:
  - url: http://localhost:8080

tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: https://swagger.io

paths:
  /pet/list:
    $ref: ./paths/list.yaml
  /pet/{id}:
    $ref: ./paths/detail.yaml
  /pet/create:
    $ref: ./paths/create.yaml
  /pet/{id}/update:
    $ref: ./paths/update.yaml
  /pet/{id}/delete:
    $ref: ./paths/delete.yaml